
export const ATTACK_COMMANDS = [
  "TARGET ACQUIRED",
  "LOCK TORPEDOES", 
  "WEAPONS READY",
  "FIRING SOLUTION",
  "ENEMY LOCKED",
  "PHASERS CHARGED",
  "TACTICAL READY",
  "ENGAGE TARGET",
  "WEAPONS HOT",
  "ATTACK VECTOR"
];

export const BATTLE_CONFIG = {
  KLINGON_SHIPS: 4,
  FEDERATION_SHIPS: 4,
  EXPLOSION_PARTICLES: 12,
  LASER_DURATION: 300,
  RETICLE_DISPLAY_TIME: 2000,
  RETICLE_FADE_TIME: 2500,
  EXPLOSION_DURATION: 1000,
  ANIMATION_FPS: 16,
  CHASE_INTERVAL: 100,
  KLINGON_FADE_INTERVAL: 1000,
  COMBAT_RANGE: 15,
  KLINGON_COMBAT_RANGE: 12,
  KLINGON_TORPEDO_RANGE: 25, // Longer range for Klingon torpedoes
  PATROL_DISTANCE: 5,
  SHIP_SPEED: 0.2, // Reduced from 0.5 for smoother movement
  TORPEDO_SPEED: 0.8, // Faster than ship movement
  SHIP_OFFSET: 1.5,
  EXPLOSION_CHANCE: 0.03, // Reduced from 0.1 for longer battles
  TORPEDO_HIT_CHANCE: 0.05, // Higher chance for torpedo hits
  KLINGON_FADE_CHANCE: 0.3,
  KLINGON_CLOAK_CHANCE: 0.2,
  FEDERATION_FIRE_CHANCE: 0.3,
  KLINGON_FIRE_CHANCE: 0.2,
  KLINGON_TORPEDO_CHANCE: 0.15, // Chance for Klingons to fire torpedoes
  PATROL_CHANGE_CHANCE: 0.05,
  TORPEDO_UPDATE_INTERVAL: 50, // How often torpedoes update position
  FEDERATION_SHIELD_STRENGTH: 100,
  SHIELD_DAMAGE_REDUCTION: 0.7, // Shields absorb 70% of damage
  SHIELD_HIT_DISPLAY_TIME: 500,
};
