
export const ATTACK_COMMANDS = [
  "TARGET ACQUIRED",
  "LOCK TORPEDOES", 
  "WEAPONS READY",
  "FIRING SOLUTION",
  "ENEMY LOCKED",
  "PHASERS CHARGED",
  "TACTICAL READY",
  "ENGAGE TARGET",
  "WEAPONS HOT",
  "ATTACK VECTOR"
];

export const BATTLE_CONFIG = {
  KLINGON_SHIPS: 4,
  FEDERATION_SHIPS: 4,
  EXPLOSION_PARTICLES: 12,
  LASER_DURATION: 300,
  RETICLE_DISPLAY_TIME: 2000,
  RETICLE_FADE_TIME: 2500,
  EXPLOSION_DURATION: 1000,
  ANIMATION_FPS: 16,
  CHASE_INTERVAL: 100,
  KLINGON_FADE_INTERVAL: 1000,
  COMBAT_RANGE: 15,
  KLINGON_COMBAT_RANGE: 12,
  PATROL_DISTANCE: 5,
  SHIP_SPEED: 0.5,
  SHIP_OFFSET: 1.5,
  EXPLOSION_CHANCE: 0.1,
  KLINGON_FADE_CHANCE: 0.3,
  KLINGON_CLOAK_CHANCE: 0.2,
  FEDERATION_FIRE_CHANCE: 0.3,
  KLINGON_FIRE_CHANCE: 0.2,
  PATROL_CHANGE_CHANCE: 0.05
};
